# Generated by Django 6.0.2 on 2026-09-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Snapshot of rbac.PRESET_ROLES at the time of this migration (migrations must
# not import live app code that may change later).
PRESET_ROLES = [
    ("Complaints Officer", "Handles student complaints and replies.",
     {"complaints": "manage", "students": "view"}),
    ("Finance Officer", "Verifies fee payments and exports finance data.",
     {"fees": "manage", "students": "view", "seats": "view", "export": "view"}),
    ("Fleet Manager", "Manages buses, drivers, routes and stops.",
     {"fleet": "manage", "routes": "manage", "incidents": "view"}),
    ("Registration Officer", "Handles registrations, seat allocation, waiting list and route changes.",
     {"seats": "manage", "route_requests": "manage", "semesters": "manage",
      "students": "view", "routes": "view", "fleet": "view"}),
    ("Safety Officer", "Reviews incident reports.",
     {"incidents": "manage", "routes": "view"}),
    ("Auditor (Read-only)", "Can view every module but cannot change anything.",
     {m: "view" for m in ["students", "semesters", "routes", "fleet", "seats", "fees",
                          "complaints", "route_requests", "incidents", "export"]}),
]


def seed_roles_and_super_admins(apps, schema_editor):
    AdminRole = apps.get_model("transport", "AdminRole")
    AdminProfile = apps.get_model("transport", "AdminProfile")
    User = apps.get_model("auth", "User")

    for name, description, perms in PRESET_ROLES:
        AdminRole.objects.get_or_create(
            name=name,
            defaults={"description": description, "permissions": perms, "is_system": True},
        )

    # Every admin that exists today becomes a super admin, so nobody loses access.
    for user in User.objects.filter(is_staff=True):
        AdminProfile.objects.get_or_create(user=user, defaults={"is_super_admin": True})


def unseed(apps, schema_editor):
    pass  # tables are dropped by the schema reversal


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0020_seatallocation_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_super_admin", models.BooleanField(default=False)),
                ("custom_permissions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admins_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admins",
                        to="transport.adminrole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("action", "Action"),
                            ("login", "Login"),
                        ],
                        max_length=10,
                    ),
                ),
                ("module", models.CharField(blank=True, default="", max_length=40)),
                ("model_name", models.CharField(blank=True, default="", max_length=80)),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="transport_a_actor_i_a5554a_idx",
                    ),
                    models.Index(
                        fields=["module", "-created_at"],
                        name="transport_a_module_37f799_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_roles_and_super_admins, unseed),
    ]
